mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('register/', views.register_account, name='register'),
    path('login/', views.login_account, name='login'),
    path('logout/', views.logout_account, name='logout'),
    path('profile/', views.get_profile, name='profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-password/', views.update_password, name='update_password'),
    path('find-username/', views.find_username, name='find_username'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('delete-account/', views.delete_account, name='delete_account'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('auth/', include('accounts.urls')),
]

mysite/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.get_post, name='read'),
    path('<int:post_id>/update/', views.update_post, name='update'),
    path('<int:post_id>/delete/', views.delete_post, name='delete'),
    path('', views.get_posts, name='list'),
    path('<int:post_id>/download/', views.posts_download, name='download'),
]

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>장고 웹 프로젝트</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- STATIC CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
        body {
            padding-top: 80px;
        }
    </style>
    {% block style %}{% endblock %}
</head>
<body>
    <div class="container">
        <!-- 네비게이션 -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">프로젝트</a>
                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'posts:list' %}">게시글</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">사용자</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auth:profile' %}">{{ user.first_name }} ({{ user.username }})</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auth:logout' %}">로그아웃</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auth:login' %}">로그인</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auth:register' %}">회원가입</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <!--// 네비게이션 -->

        <!-- 페이지 제목 -->
        {% block page_title %}{% endblock %}
        <!--// 페이지 제목 -->
        
        <!-- 메시지 -->
        {% if messages %}
            <div class="row">
                <div class="{% if message_class %}{{ message_class }}{% else %}col-12{% endif %}">
                    {% for message in messages %}
                        {% if message.tags == "error" %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endif %}
                        {% if message.tags == "success" %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <!--// 메시지 -->

        <!-- 페이지 내용 -->
        {% block content %}{% endblock %}
        <!--// 페이지 내용 -->
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- jQuery-->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
    <!-- jQuery Validation -->
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/additional-methods.min.js"></script>
    <!-- tinymce -->
    <script src="{% static 'tinymce/tinymce.min.js' %}"></script>
    <!-- STATIC JS -->
    <script src="{% static 'script.js' %}"></script>
    <script>
        /* 자바스크립트 */
    </script>
    {% block script %}{% endblock %}
</body>
</html>

mysite/templates/default.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>장고 웹 프로젝트</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- STATIC CSS -->
    <link rel="stylesheet" href="static/style.css">
    <style>
        body {
            padding-top: 100px;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- 네비게이션 -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">프로젝트</a>
                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" href="#">게시글</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">사용자</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item">
                                <a class="nav-link" href="#">로그인</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <!--// 네비게이션 -->

        <!-- 페이지 제목 -->
        <div class="row">
            <div class="col-12">
                <h1>페이지 제목</h1>
            </div>
        </div>
        <!--// 페이지 제목 -->
        
        <!-- 메시지 -->
        <div class="row">
            <div class="col-12">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    성공 메시지
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    실패 메시지
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
        <!--// 메시지 -->

        <!-- 페이지 내용 -->
        <div class="row">
            <div class="col-12">
                페이지 내용
            </div>
        </div>
        <!--// 페이지 내용 -->
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- STATIC JS -->
    <script src="static/script.js"></script>
    <script>
        /* 자바스크립트 */
    </script>
</body>
</html>