mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('auth/', include('accounts.urls')),
]

mysite/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.get_post, name='read'),
    path('<int:post_id>/update/', views.update_post, name='update'),
    path('<int:post_id>/delete/', views.delete_post, name='delete'),
    path('', views.get_posts, name='list'),
    path('<int:post_id>/download/', views.posts_download, name='download'),
]

mysite/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# 게시글 모델
class Posts(models.Model):
    title = models.CharField(verbose_name="제목", max_length=100)
    content = models.TextField(verbose_name="내용")
    password = models.CharField(verbose_name="비밀번호", max_length=100)
    username = models.CharField(verbose_name="글쓴이", max_length=10)
    filename = models.CharField(verbose_name="파일명", max_length=100, null=True, blank=True)
    original_filename = models.CharField(verbose_name="원본파일명", max_length=100, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="작성자", null=True, blank=True, related_name="posts_created_by")
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="수정자", null=True, blank=True, related_name="posts_updated_by")
    created_at = models.DateTimeField(verbose_name="작성일시", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="수정일시", auto_now=True)
    
    class Meta:
        db_table = 'posts'
        verbose_name = "게시글"
        verbose_name_plural = "게시글 목록"

    def __str__(self):
        return self.title

mysite/posts/forms.py
from django import forms
from .models import Posts

# 게시글 등록 폼
class PostCreateForm(forms.ModelForm):
    title = forms.CharField(required=False)
    content = forms.CharField(required=False)
    
    class Meta:
        model = Posts
        fields = ['title', 'content']
        
    # 제목 검증
    def clean_title(self):
        title = self.cleaned_data['title']
        if not title:
            raise forms.ValidationError("제목을 입력해주세요.")
        if len(title) < 2:
            raise forms.ValidationError("제목은 최소 2자 이상 입력해주세요.")
        if len(title) > 100:
            raise forms.ValidationError("제목은 최대 100자 이하로 입력해주세요.")
        return title
    
    # 내용 검증
    def clean_content(self):
        content = self.cleaned_data['content']
        if not content:
            raise forms.ValidationError("내용을 입력해주세요.")
        return content

# 게시글 수정 폼
class PostUpdateForm(forms.ModelForm):
    title = forms.CharField(required=False)
    content = forms.CharField(required=False)
    
    class Meta:
        model = Posts
        fields = ['title', 'content']
        
    # 제목 검증
    def clean_title(self):
        title = self.cleaned_data['title']
        if not title:
            raise forms.ValidationError("제목을 입력해주세요.")
        if len(title) < 2:
            raise forms.ValidationError("제목은 최소 2자 이상 입력해주세요.")
        if len(title) > 100:
            raise forms.ValidationError("제목은 최대 100자 이하로 입력해주세요.")
        return title
    
    # 내용 검증
    def clean_content(self):
        content = self.cleaned_data['content']
        if not content:
            raise forms.ValidationError("내용을 입력해주세요.")
        return content

mysite/posts/views.py
import os
import uuid
from urllib.parse import quote

from django.http import HttpResponse
from mysite import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from .models import Posts
from .forms import PostCreateForm, PostUpdateForm

# 게시글 등록
@login_required(login_url='auth:login')
def create_post(request):
    form = PostCreateForm()
    
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.created_by = request.user
            post.updated_by = request.user
            post.save()
            
            # 파일 업로드
            if request.FILES.get('uploadFile'):
                filename = uuid.uuid4().hex
                file = request.FILES.get('uploadFile')
                
                # 파일 저장 경로
                file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(filename))
                if not os.path.exists(os.path.dirname(file_path)):
                    os.makedirs(os.path.dirname(file_path))
                
                # 파일 저장
                with open(file_path, 'wb') as f:
                    for chunk in file.chunks():
                        f.write(chunk)
                
                post.filename = filename
                post.original_filename = file.name
                post.save()
            
            messages.success(request, '게시글이 등록되었습니다.')
            return redirect("posts:read", post_id=post.id)
        else:
            messages.error(request, '게시글 등록에 실패했습니다.')
    
    return render(request, 'posts/create.html', {'form': form})

# 게시글 보기
@login_required(login_url='auth:login')
def get_post(request, post_id):
    post = get_object_or_404(Posts, id=post_id)
    return render(request, 'posts/read.html', {'post': post})

# 게시글 수정
@login_required(login_url='auth:login')
def update_post(request, post_id):
    post = get_object_or_404(Posts, id=post_id) 
       
    if post.created_by != request.user:
        messages.error(request, '게시글을 수정 권한이 없습니다.')
        return redirect('posts:read', post_id=post.id)
    
    form = PostUpdateForm(instance=post)
    
    if request.method == 'POST':
        form = PostUpdateForm(request.POST)
        
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.updated_by = request.user
            post.save()
                
            # 파일 삭제
            if request.POST.get('deleteFile'):
                if post.filename:
                    # 파일 삭제
                    file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(post.filename))    
                    if os.path.exists(file_path):
                        os.remove(file_path)
                    
                    post.filename = None
                    post.original_filename = None
                    post.save()

            # 파일 업로드
            if request.FILES.get('uploadFile'):
                if post.filename:
                    # 파일 삭제
                    file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(post.filename))    
                    if os.path.exists(file_path):
                        os.remove(file_path)
                    
                filename = uuid.uuid4().hex
                file = request.FILES.get('uploadFile')
                
                # 파일 저장 경로
                file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(filename))
                if not os.path.exists(os.path.dirname(file_path)):
                    os.makedirs(os.path.dirname(file_path))
                
                # 파일 저장
                with open(file_path, 'wb') as f:
                    for chunk in file.chunks():
                        f.write(chunk)
                        
                post.filename = filename
                post.original_filename = file.name
                post.save()
                
            messages.success(request, '게시글이 수정되었습니다.')
            return redirect('posts:read', post_id=post.id)
        else:
            messages.error(request, '게시글 수정에 실패했습니다.')

    return render(request, 'posts/update.html', {'form': form})

# 게시글 삭제
@login_required(login_url='auth:login')
def delete_post(request, post_id):
    post = get_object_or_404(Posts, id=post_id)
    
    if post.created_by != request.user:
        messages.error(request, '게시글을 삭제 권한이 없습니다.')
        return redirect('posts:read', post_id=post.id)
    
    if request.method == 'POST':
        # 파일 삭제
        if post.filename:
            file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(post.filename))    
            if os.path.exists(file_path):
                os.remove(file_path)
        
        post.delete()
        messages.success(request, '게시글이 삭제되었습니다.')
        return redirect('posts:list')

# 게시글 목록
@login_required(login_url='auth:login')
def get_posts(request):    
    page = request.GET.get('page', '1') 
    searchType = request.GET.get('searchType')
    searchKeyword = request.GET.get('searchKeyword')
    posts = Posts.objects.all().order_by('-created_at')
    
    # 검색 조건 처리
    if searchType not in [None, ''] and searchKeyword not in [None, '']:
        if searchType == 'all':
            posts = posts.filter(
                Q(title__contains=searchKeyword) | 
                Q(content__contains=searchKeyword) | 
                Q(username__contains=searchKeyword)
            )
        elif searchType == 'title':
            posts = posts.filter(
                Q(title__contains=searchKeyword)
            )
        elif searchType == 'content':
            posts = posts.filter(
                Q(content__contains=searchKeyword)
            )
        elif searchType == 'full_name':
            posts = posts.filter(
                Q(created_by__first_name__contains=searchKeyword)
            )
    
    # 페이지네이션
    paginator = Paginator(posts, 10)
    page_obj = paginator.get_page(page)
    
    # 현재 페이지의 첫 번째 게시글 번호 계산
    start_index = paginator.count - (paginator.per_page * (page_obj.number - 1))
    
    # 순번 계산하여 게시글 리스트에 추가
    for index, _ in enumerate(page_obj, start=0):
        page_obj[index].index_number = start_index - index
    
    return render(request, 'posts/list.html', {
        'posts': page_obj,
        'searchType': searchType,
        'searchKeyword': searchKeyword
    })
    
# 첨부 파일 다운로드
@login_required(login_url='auth:login')
def posts_download(request, post_id):
    post = get_object_or_404(Posts, id=post_id)
    file_path = os.path.join(settings.MEDIA_ROOT, 'posts', str(post.id), str(post.filename))
    
    if os.path.exists(file_path):
        with open(file_path, 'rb') as file:
            response = HttpResponse(file.read(), content_type='application/octet-stream')
            encoded_filename = quote(post.original_filename)
            response['Content-Disposition'] = f'attachment; filename*=UTF-8\'\'{encoded_filename}'
            return response
    
    return HttpResponse(status=404)

mysite/templates/posts/create.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <!-- 게시글 등록 -->
        <form id="createForm" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card mb-3">
                <div class="card-header">
                    <span class="text-danger">*</span> 표시는 필수항목입니다.
                </div>
                <div class="card-body">            
                    <div class="mb-3">
                        <label for="title" class="form-label">제목 <span class="text-danger">*</span></label>
                        <input type="text" id="title" name="title" class="form-control" placeholder="제목을 입력하세요." value="{{ form.title.value|default_if_none:'' }}">
                        {% if form.title.errors %}
                        <div class="form-text text-danger">
                            {{ form.title.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="content" class="form-label">내용 <span class="text-danger">*</span></label>
                        <textarea rows="10" id="content" name="content" class="form-control" placeholder="내용을 입력하세요.">{{ form.content.value|default_if_none:'' }}</textarea>
                        {% if form.content.errors %}
                        <div class="form-text text-danger">
                            {{ form.content.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div>
                        <label for="uploadFile" class="form-label">첨부 파일</label>
                        <input type="file" class="form-control" id="uploadFile" name="uploadFile" accept="image/*">
                    </div>
                </div>                
            </div>
            <div>
                <button type="submit" class="btn btn-primary">등록</button>
                <a href="{% url 'posts:list' %}" class="btn btn-secondary">취소</a>
            </div>
        </form>
        <!--// 게시글 등록 -->
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        // TinyMCE 초기화
        tinymce.init({
            selector: '#content',
            language: 'ko_KR',
            // TinyMCE 필수 입력 설정
            setup: function(editor) {
                editor.on('change', function() {
                    editor.save(); // 에디터 내용을 textarea에 반영
                    validateContent(); // 컨텐츠 유효성 검사
                });
            }
        });

        // 컨텐츠 유효성 검사 함수
        function validateContent() {
            var content = tinymce.get('content').getContent();
            var textContent = $('<div>').html(content).text(); // HTML 태그 제거

            if (textContent.length < 2) {
                $('#content').addClass('is-invalid');
                $('#content-error').remove();
                $('#content').closest('.mb-3').append('<div id="content-error" class="invalid-feedback">내용은 최소 2자 이상 입력하세요.</div>');
                return false;
            } else if (textContent.length > 1000) {
                $('#content').addClass('is-invalid');
                $('#content-error').remove();
                $('#content').closest('.mb-3').append('<div id="content-error" class="invalid-feedback">내용은 최대 1000자 이하로 입력하세요.</div>');
                return false;
            } else {
                $('#content').removeClass('is-invalid').addClass('is-valid');
                $('#content-error').remove();
                return true;
            }
        }

        // 게시글 폼 검증
        $('#createForm').validate({
            rules: {
                title: {
                    required: true,
                    minlength: 2,
                    maxlength: 100
                }
            },
            messages: {
                title: {
                    required: '제목을 입력하세요.',
                    minlength: '제목은 최소 2자 이상 입력하세요.',
                    maxlength: '제목은 최대 100자 이하로 입력하세요.'
                }
            },
            errorClass: 'is-invalid',
            validClass: 'is-valid',
            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            submitHandler: function(form) {
                // 폼 제출 전 내용 검증
                if (validateContent()) {
                    form.submit();
                }
                return false;
            }
        });
    });
</script>
{% endblock %}

mysite/templates/posts/list.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">    
        <!-- 검색, 등록 버튼 -->
        <div class="d-flex justify-content-between">
            <!-- 검색 폼 -->
            <form method="GET">
                <div class="input-group">
                    <select name="searchType" class="form-select w-auto">
                        <option value="all" {% if searchType == 'all' %}selected{% endif %}>전체</option>
                        <option value="title" {% if searchType == 'title' %}selected{% endif %}>제목</option>
                        <option value="content" {% if searchType == 'content' %}selected{% endif %}>내용</option>
                        <option value="first_name" {% if searchType == 'first_name' %}selected{% endif %}>작성자</option>
                    </select>
                    <input type="text" name="searchKeyword" class="form-control w-auto" value="{{ searchKeyword|default_if_none:'' }}" placeholder="검색어를 입력하세요">
                    <button type="submit" class="btn btn-primary">검색</button>
                    {% if searchType != null %}
                        <a href="{% url 'posts:list' %}" class="btn btn-danger">취소</a>
                    {% endif %}
                </div>
            </form>        
            <!-- 등록 버튼 -->
            <a href="{% url 'posts:create' %}" class="btn btn-primary">등록</a>
        </div>
        <!--// 검색, 등록 버튼 -->
    </div>
</div>
<div class="row">
    <div class="col-12">
        <!-- 게시글 목록 -->
        <div class="table-responsive">
            <table class="table table-bordered mt-3">
                <thead>
                <tr class="text-center">
                    <th>순번</th>
                    <th>제목</th>
                    <th>글쓴이</th>
                    <th>등록일시</th>
                    <th>수정일시</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td class="text-center">{{ post.index_number }}</td>
                        <td><a href="{% url 'posts:read' post_id=post.id %}">{{ post.title }}</a></td>
                        <td class="text-center">{{ post.created_by.first_name }}</td>
                        <td class="text-center">{{ post.created_at | date:"Y-m-d H:i" }}</td>
                        <td class="text-center">{{ post.updated_at | date:"Y-m-d H:i" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!--// 게시글 목록 -->
    </div>
</div>
<div class="row">
    <div class="col-12">
        <!-- 페이지네이션 -->
        <div>
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    <!-- 이전 페이지 -->
                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.previous_page_number }}">이전</a>
                        </li>
                    {% endif %}
                    <!--// 이전 페이지 -->                        
                    <!-- 페이지 리스트 -->
                    {% for page_number in posts.paginator.page_range %}
                        {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}
                            <li class="page-item {% if page_number == posts.number %}active{% endif %}">
                                <a class="page-link" href="{% url 'posts:list' %}?page={{ page_number }}">
                                    {{ page_number }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    <!--// 페이지 리스트 -->        
                    <!-- 다음 페이지 -->
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.next_page_number }}">다음</a>
                        </li>
                    {% endif %}
                    <!--// 다음 페이지 -->
                </ul>
              </nav>
        </div>
        <!--// 페이지네이션 -->
    </div>
</div>
{% endblock %}

mysite/templates/posts/read.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <!-- 게시글 보기 -->
        <div class="card mb-3">
            <h5 class="card-header text-primary">
                <strong>{{ post.title }}</strong>
            </h5>
            <div class="card-body">  
                <div class="mb-3 text-muted">
                    글쓴이: {{ post.created_by.first_name }} | 등록일시: {{ post.created_at | date:"Y-m-d H:i" }} | 수정일시: {{ post.updated_at | date:"Y-m-d H:i" }}
                </div>
                {% if post.filename %}
                <div class="mb-3 text-muted">
                    첨부 파일: <a href="{% url 'posts:download' post.id %}">{{ post.original_filename }}</a>
                </div>
                {% endif %}
                <div class="mb-3">
                    {{ post.content | safe }}
                </div>
            </div>
        </div>
        <div>
            <a href="{% url 'posts:list' %}" class="btn btn-primary">목록</a>
            {% if post.created_by == request.user %}
            <a href="{% url 'posts:update' post_id=post.id %}" class="btn btn-warning">수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">삭제</button>
            {% endif %}
        </div>
        <!--// 게시글 보기 -->
    </div>
</div>

<!-- 삭제 모달 -->
{% if post.created_by == request.user %}
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="deleteForm" action="{% url 'posts:delete' post_id=post.id %}" method="POST">
                {% csrf_token %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-danger" id="deleteModalModalLabel">
                        <strong>게시글 삭제</strong>
                    </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <p class="text-danger">삭제된 데이터는 복구할 수 없습니다.</p>
                        <p>비밀번호를 입력해주세요.</p>
                    </div>
                    <div>
                        <input type="password" id="password" name="password" placeholder="비밀번호" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-danger">삭제</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}
<!-- 삭제 모달 -->
{% endblock %}

mysite/templates/posts/update.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-12">
        <!-- 게시글 수정 -->
        <form id="updateForm" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card mb-3">
                <div class="card-header">
                    <span class="text-danger">*</span> 표시는 필수항목입니다.
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <label for="title" class="form-label">제목 <span class="text-danger">*</span></label>
                        <input type="text" id="title" name="title" class="form-control" placeholder="제목을 입력하세요." value="{{ form.title.value|default_if_none:'' }}">
                        {% if form.title.errors %}
                        <div class="form-text text-danger">
                            {{ form.title.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="content" class="form-label">내용 <span class="text-danger">*</span></label>
                        <textarea rows="10" id="content" name="content" class="form-control" placeholder="내용을 입력하세요.">{{ form.content.value|default_if_none:'' }}</textarea>
                        {% if form.content.errors %}
                        <div class="form-text text-danger">
                            {{ form.content.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    {% if form.instance.filename %}
                    <div class="mb-3">
                        <div class="mb-2">  
                            <span>기존 파일: <a href="{% url 'posts:download' form.instance.id %}">{{ form.instance.original_filename }}</a></span>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="deleteFile" id="deleteFile" value="false">
                            <label class="form-check-label text-danger" for="deleteFile">
                                파일 삭제
                            </label>
                        </div>
                    </div>
                    {% endif %}
                    <div>
                        <label for="uploadFile" class="form-label">첨부 파일</label>
                        <input type="file" class="form-control" id="uploadFile" name="uploadFile" accept="image/*">
                    </div>
                </div>
            </div>
            <div>
                <button type="submit" class="btn btn-primary">수정</button>
                
            </div>
        </form>
        <!--// 게시글 수정 -->
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        // TinyMCE 초기화
        tinymce.init({
            selector: '#content',
            language: 'ko_KR',
            // TinyMCE 필수 입력 설정
            setup: function(editor) {
                editor.on('change', function() {
                    editor.save(); // 에디터 내용을 textarea에 반영
                    validateContent(); // 컨텐츠 유효성 검사
                });
            }
        });

        // 컨텐츠 유효성 검사 함수
        function validateContent() {
            var content = tinymce.get('content').getContent();
            var textContent = $('<div>').html(content).text(); // HTML 태그 제거

            if (textContent.length < 2) {
                $('#content').addClass('is-invalid');
                $('#content-error').remove();
                $('#content').closest('.mb-3').append('<div id="content-error" class="invalid-feedback">내용은 최소 2자 이상 입력하세요.</div>');
                return false;
            } else if (textContent.length > 1000) {
                $('#content').addClass('is-invalid');
                $('#content-error').remove();
                $('#content').closest('.mb-3').append('<div id="content-error" class="invalid-feedback">내용은 최대 1000자 이하로 입력하세요.</div>');
                return false;
            } else {
                $('#content').removeClass('is-invalid').addClass('is-valid');
                $('#content-error').remove();
                return true;
            }
        }

        // 게시글 폼 검증
        $('#updateForm').validate({
            rules: {
                title: {
                    required: true,
                    minlength: 2,
                    maxlength: 100
                }
            },
            messages: {
                title: {
                    required: '제목을 입력하세요.',
                    minlength: '제목은 최소 2자 이상 입력하세요.',
                    maxlength: '제목은 최대 100자 이하로 입력하세요.'
                }
            },
            errorClass: 'is-invalid',
            validClass: 'is-valid',
            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            submitHandler: function(form) {
                // 폼 제출 전 내용 검증
                if (validateContent()) {
                    form.submit();
                }
                return false;
            }
        });
    });
</script>
{% endblock %}