mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('register/', views.register_account, name='register'),
    path('login/', views.login_account, name='login'),
    path('logout/', views.logout_account, name='logout'),
    path('profile/', views.get_profile, name='profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('update-password/', views.update_password, name='update_password'),
    path('find-username/', views.find_username, name='find_username'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('delete-account/', views.delete_account, name='delete_account'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('auth/', include('accounts.urls')),
]

mysite/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.get_post, name='read'),
    path('<int:post_id>/update/', views.update_post, name='update'),
    path('<int:post_id>/delete/', views.delete_post, name='delete'),
    path('', views.get_posts, name='list'),
    path('<int:post_id>/download/', views.posts_download, name='download'),
]

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/accounts/forms.py
import re
from django import forms
from django.contrib.auth.models import User

# 회원가입 폼
class RegisterForm(forms.ModelForm):
    username = forms.CharField(required=False)
    password1 = forms.CharField(required=False)
    password2 = forms.CharField(required=False)
    first_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'email']
        
    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not username:
            raise forms.ValidationError("아이디를 입력해주세요.")
        if len(username) < 6:
            raise forms.ValidationError("아이디는 최소 6글자 이상 입력해주세요.")
        if len(username) > 20:
            raise forms.ValidationError("아이디는 최대 20글자 이하로 입력해주세요.")        
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("이미 사용중인 아이디입니다.")
        return username

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if not password1:
            raise forms.ValidationError("비밀번호를 입력해주세요.")
        if len(password1) < 8:
            raise forms.ValidationError("비밀번호는 최소 8글자 이상 입력해주세요.")
        
        # 비밀번호 복잡성 검증
        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError("비밀번호는 최소 1개의 숫자를 포함해야 합니다.")
        if not any(char.isupper() for char in password1):
            raise forms.ValidationError("비밀번호는 최소 1개의 대문자를 포함해야 합니다.")
        if not any(char.islower() for char in password1):
            raise forms.ValidationError("비밀번호는 최소 1개의 소문자를 포함해야 합니다.")
        if not any(char in "!@#$%^&*()_+-=[]{}|;:,.<>?" for char in password1):
            raise forms.ValidationError("비밀번호는 최소 1개의 특수문자를 포함해야 합니다.")
        
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if not password2:
            raise forms.ValidationError("비밀번호 확인을 입력해주세요.")
        if password1 != password2:
            raise forms.ValidationError("비밀번호와 비밀번호 확인이 일치하지 않습니다.")
        return password2

    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not first_name:
            raise forms.ValidationError("이름을 입력해주세요.")
        if len(first_name) < 2:
            raise forms.ValidationError("이름은 최소 2글자 이상 입력해주세요.")
        if len(first_name) > 4:
            raise forms.ValidationError("이름은 최대 4글자 이하로 입력해주세요.")
        return first_name 

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not email:
            raise forms.ValidationError("이메일을 입력해주세요.")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("이미 사용중인 이메일입니다.")
        if len(email) > 50:
            raise forms.ValidationError("이메일은 최대 50글자 이하로 입력해주세요.")
        if not re.match(r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email):
            raise forms.ValidationError("이메일 형식이 올바르지 않습니다.")
        return email

# 로그인 폼
class LoginForm(forms.Form):
    username = forms.CharField(required=False)
    password = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ["username", "password"]

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not username:
            raise forms.ValidationError("아이디를 입력해주세요.")
        return username

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not password:
            raise forms.ValidationError("비밀번호를 입력해주세요.")
        return password

# 프로필 수정 폼
class ProfileUpdateForm(forms.ModelForm):
    first_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    
    class Meta:
        model = User
        fields = ['first_name', 'email']
        
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not first_name:
            raise forms.ValidationError("이름을 입력해주세요.")
        if len(first_name) < 2:
            raise forms.ValidationError("이름은 최소 2글자 이상 입력해주세요.")
        if len(first_name) > 4:
            raise forms.ValidationError("이름은 최대 4글자 이하로 입력해주세요.")
        return first_name 

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not email:
            raise forms.ValidationError("이메일을 입력해주세요.")
        print(self.instance.id)
        if User.objects.filter(email=email).exclude(id=self.instance.id).exists():
            raise forms.ValidationError("이미 사용중인 이메일입니다.")
        if len(email) > 50:
            raise forms.ValidationError("이메일은 최대 50글자 이하로 입력해주세요.")
        if not re.match(r'^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email):
            raise forms.ValidationError("이메일 형식이 올바르지 않습니다.")
        return email
    
# 비밀번호 수정 폼
class PasswordUpdateForm(forms.Form):
    password = forms.CharField(required=False)
    password1 = forms.CharField(required=False)
    password2 = forms.CharField(required=False)
    
    class Meta:
        model = User
        fields = ['password', 'password1', 'password2']
    
    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not password:
            raise forms.ValidationError("비밀번호를 입력해주세요.")
        return password

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if not password1:
            raise forms.ValidationError("비밀번호를 입력해주세요.")
        if len(password1) < 8:
            raise forms.ValidationError("비밀번호는 최소 8글자 이상 입력해주세요.")
        
        # 비밀번호 복잡성 검증
        if not any(char.isdigit() for char in password1):
            raise forms.ValidationError("비밀번호는 최소 1개의 숫자를 포함해야 합니다.")
        if not any(char.isupper() for char in password1):
            raise forms.ValidationError("비밀번호는 최소 1개의 대문자를 포함해야 합니다.")
        if not any(char.islower() for char in password1):
            raise forms.ValidationError("비밀번호는 최소 1개의 소문자를 포함해야 합니다.")
        if not any(char in "!@#$%^&*()_+-=[]{}|;:,.<>?" for char in password1):
            raise forms.ValidationError("비밀번호는 최소 1개의 특수문자를 포함해야 합니다.")
        
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if not password2:
            raise forms.ValidationError("비밀번호 확인을 입력해주세요.")
        if password1 != password2:
            raise forms.ValidationError("비밀번호와 비밀번호 확인이 일치하지 않습니다.")
        return password2
    
# 아이디 찾기 폼
class UsernameFindForm(forms.Form):
    first_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    
    class Meta:
        model = User
        fields = ['first_name', 'email']
        
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not first_name:
            raise forms.ValidationError("이름을 입력해주세요.")
        return first_name 

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not email:
            raise forms.ValidationError("이메일을 입력해주세요.")
        return email
    
# 비밀번호 초기화 폼
class PasswordResetForm(forms.Form):
    first_name = forms.CharField(required=False)
    username = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    
    class Meta:
        model = User
        fields = ['first_name', 'username', 'email']
        
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not first_name:
            raise forms.ValidationError("이름을 입력해주세요.")
        return first_name 
    
    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not username:
            raise forms.ValidationError("아이디를 입력해주세요.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not email:
            raise forms.ValidationError("이메일을 입력해주세요.")
        return email
    
# 회원탈퇴 폼
class AccountDeleteForm(forms.Form):
    first_name = forms.CharField(required=False)
    username = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    password = forms.CharField(required=False)
    
    class Meta:
        model = User
        fields = ['first_name', 'username', 'email', 'password']
        
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if not first_name:
            raise forms.ValidationError("이름을 입력해주세요.")
        return first_name 
    
    def clean_username(self):
        username = self.cleaned_data.get("username")
        if not username:
            raise forms.ValidationError("아이디를 입력해주세요.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not email:
            raise forms.ValidationError("이메일을 입력해주세요.")
        return email
    
    def clean_password(self):
        password = self.cleaned_data.get("password")
        if not password:
            raise forms.ValidationError("비밀번호를 입력해주세요.")
        return password

mysite/accounts/views.py
import random
import string
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User

from .forms import AccountDeleteForm, UsernameFindForm, LoginForm, PasswordResetForm, RegisterForm, PasswordUpdateForm, ProfileUpdateForm

# 회원가입
def register_account(request):
    if request.user.is_authenticated:
        return redirect('auth:profile')

    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password1"],
                first_name=form.cleaned_data["first_name"],
                email=form.cleaned_data["email"]
            )
            user.save()
            messages.success(request, '회원가입이 완료되었습니다.')
            return redirect('auth:login')
        else:
            messages.error(request, '회원가입에 실패했습니다.')

    return render(request, 'accounts/register.html', {'form': form, 'message_class': 'col-4 mx-auto'})

# 로그인
def login_account(request):
    if request.user.is_authenticated:
        return redirect('auth:profile')
    
    form = LoginForm()
    
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            # 로그인 실패
            if user is None:
                messages.error(request, '아이디 또는 비밀번호가 일치하지 않습니다.')
                return redirect('auth:login')

            # 로그인 성공
            login(request, user)
            return redirect('auth:profile')
        else:
            messages.error(request, '아이디 또는 비밀번호를 입력해주세요.')

    return render(request, 'accounts/login.html', {'form': form, 'message_class': 'col-4 mx-auto'})

# 로그아웃
def logout_account(request):
    logout(request)
    return redirect('auth:login')

# 프로필 보기
@login_required(login_url='auth:login')
def get_profile(request):    
    return render(request, 'accounts/profile.html', {'message_class': 'col-4 mx-auto'})

# 프로필 수정
@login_required(login_url='auth:login')
def update_profile(request):
    form = ProfileUpdateForm(instance=request.user)

    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            update_session_auth_hash(request, user)
            messages.success(request, '프로필 수정이 완료되었습니다.')
            return redirect('auth:profile')
        else:
            messages.error(request, '프로필 수정에 실패했습니다.')

    return render(request, 'accounts/update_profile.html', {'form': form, 'message_class': 'col-4 mx-auto'})

# 비밀번호 수정
@login_required(login_url='auth:login')
def update_password(request):
    form = PasswordUpdateForm()

    if request.method == 'POST':
        form = PasswordUpdateForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            password1 = form.cleaned_data['password1']

            user = authenticate(request, username=request.user.username, password=password)
            if user is None:
                messages.error(request, '기존 비밀번호가 일치하지 않습니다.')
                return redirect('auth:update_password')

            user = request.user
            user.set_password(password1)
            user.save()

            logout(request)
            messages.success(request, '비밀번호 수정이 완료되었습니다. 다시 로그인해주세요.')
            return redirect('auth:login')
        else:
            messages.error(request, '비밀번호 수정에 실패했습니다.')

    return render(request, 'accounts/update_password.html', {'form': form, 'message_class': 'col-4 mx-auto'})

# 아이디 찾기
def find_username(request):
    if request.user.is_authenticated:
        return redirect('auth:profile')
    
    form = UsernameFindForm()

    if request.method == 'POST':
        form = UsernameFindForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            email = form.cleaned_data['email']
            user = User.objects.filter(first_name=first_name, email=email).first()
            if user:
                messages.success(request, f'아이디는 {user.username}입니다.')
                return redirect('auth:login')
            else:
                messages.error(request, '아이디 찾기에 실패했습니다.')
        else:
            messages.error(request, '아이디 찾기에 실패했습니다.')

    return render(request, 'accounts/find_username.html', {'form': form, 'message_class': 'col-4 mx-auto'})

# 비밀번호 초기화
def reset_password(request):
    if request.user.is_authenticated:
        return redirect('auth:profile')
    
    form = PasswordResetForm()

    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            user = User.objects.filter(first_name=first_name, username=username, email=email).first()
            if user:
                password = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
                user.set_password(password)
                user.save()

                messages.success(request, f'비밀번호가 초기화되었습니다. 새로운 비밀번호는 {password}입니다.')
                return redirect('auth:login')
            else:
                messages.error(request, '비밀번호 초기화에 실패했습니다.')

    return render(request, 'accounts/reset_password.html', {'form': form, 'message_class': 'col-4 mx-auto'})

# 탈퇴
@login_required(login_url='auth:login')
def delete_account(request):
    form = AccountDeleteForm()

    if request.method == 'POST':
        form = AccountDeleteForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.filter(first_name=first_name, username=username, email=email).first()
            authenticated = authenticate(request, username=username, password=password)
            if user and authenticated is not None:
                user.delete()
                logout(request)
                messages.success(request, '회원탈퇴가 완료되었습니다.')
                return redirect('auth:login')
            else:
                messages.error(request, '회원탈퇴에 실패했습니다. 입력정보를 확인하세요.')

    return render(request, 'accounts/delete_account.html', {'form': form, 'message_class': 'col-4 mx-auto'})

mysite/templates/accounts/find_username.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-4 mx-auto">
        <!-- 아이디 찾기 -->
        <form id="findUsernameForm" method="POST">
            {% csrf_token %}
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">아이디 찾기</h5>
                </div>
                <div class="card-body">     
                    <div class="mb-3">
                        <label for="first_name" class="form-label">이름 <span class="text-danger">*</span></label>
                        <input type="text" id="first_name" name="first_name" class="form-control" placeholder="이름을 입력하세요." value="{{ form.first_name.value|default_if_none:'' }}">
                        {% if form.first_name.errors %}
                        <div class="form-text text-danger">
                            {{ form.first_name.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">이메일 <span class="text-danger">*</span></label>
                        <input type="email" id="email" name="email" class="form-control" placeholder="이메일을 입력하세요." value="{{ form.email.value|default_if_none:'' }}">
                        {% if form.email.errors %}
                        <div class="form-text text-danger">
                            {{ form.email.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                </div>                
            </div>
            <div>
                <button type="submit" class="btn btn-primary">아이디 찾기</button>
                <a href="{% url 'auth:reset_password' %}" class="btn btn-danger">비밀번호 초기화</a>
                <a href="{% url 'auth:login' %}" class="btn btn-secondary">로그인</a>
            </div>
        </form>
        <!--// 아이디 찾기 -->
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        // 아이디 찾기 폼 검증
        $('#findUsernameForm').validate({
            rules: {
                first_name: {
                    required: true,
                },
                email: {
                    required: true,
                }
            },
            messages: {
                first_name: {
                    required: '이름을 입력하세요.',
                },
                email: {
                    required: '이메일을 입력하세요.',
                }
            },
            errorClass: 'is-invalid',
            validClass: 'is-valid',
            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>
{% endblock %}

mysite/templates/accounts/login.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-4 mx-auto">
        <!-- 로그인 -->
        <form id="loginForm" method="POST">
            {% csrf_token %}
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">로그인</h5>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <label for="username" class="form-label">아이디 <span class="text-danger">*</span></label>
                        <input type="text" id="username" name="username" class="form-control" placeholder="아이디를 입력하세요." value="{{ form.username.value|default_if_none:'' }}">
                        {% if form.username.errors %}
                        <div class="form-text text-danger">
                            {{ form.username.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">비밀번호 <span class="text-danger">*</span></label>
                        <input type="password" id="password" name="password" class="form-control" placeholder="비밀번호를 입력하세요.">
                        {% if form.password.errors %}
                        <div class="form-text text-danger">
                            {{ form.password.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary">로그인</button>
                    </div>
                </div>                
            </div>
            <div class="text-center">
                <a href="{% url 'auth:register' %}" class="btn btn-success mx-2">회원가입</a>
                <a href="{% url 'auth:find_username' %}" class="btn btn-warning mx-2">아이디 찾기</a>
                <a href="{% url 'auth:reset_password' %}" class="btn btn-danger mx-2">비밀번호 초기화</a>
            </div>
        </form>
        <!--// 로그인 -->
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        // 로그인 폼 검증
        $('#loginForm').validate({
            rules: {
                username: {
                    required: true,
                },
                password: {
                    required: true,
                },
            },
            messages: {
                username: {
                    required: '아이디를 입력하세요.',
                },
                password: {
                    required: '비밀번호를 입력하세요.',
                },
            },
            errorClass: 'is-invalid',
            validClass: 'is-valid',
            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>
{% endblock %}

mysite/templates/accounts/profile.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-4 mx-auto">
        <!-- 프로필 -->
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title">프로필</h5>
            </div>
            <div class="card-body">
                <p class="card-text">
                    <div class="d-flex justify-content-between">
                        <span class="text-muted">아이디</span>
                        {{ user.username }}
                    </div>
                </p>
                <hr>
                <p class="card-text">
                    <div class="d-flex justify-content-between">
                        <span class="text-muted">이름</span>
                        {{ user.first_name }}
                    </div>
                </p>
                <hr>
                <p class="card-text">
                    <div class="d-flex justify-content-between">
                        <span class="text-muted">이메일</span>
                        {{ user.email }}
                    </div>
                </p>
            </div>
        </div>
        <!--// 프로필 -->
        <div class="text-center">
            <a href="{% url 'auth:update_profile' %}" class="btn btn-success mx-2">프로필 수정</a>
            <a href="{% url 'auth:update_password' %}" class="btn btn-warning mx-2">비밀번호 변경</a>
            <a href="{% url 'auth:delete_account' %}" class="btn btn-danger mx-2">회원탈퇴</a>
        </div>
    </div>
</div>
{% endblock %}

mysite/templates/accounts/reset_password.html
{% extends "../base.html" %}

{% block content %}
<div class="row">
    <div class="col-4 mx-auto">
        <!-- 비밀번호 초기화 -->
        <form id="resetPasswordForm" method="POST">
            {% csrf_token %}
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="card-title">비밀번호 초기화</h5>
                </div>
                <div class="card-body">     
                    <div class="mb-3">
                        <label for="first_name" class="form-label">이름 <span class="text-danger">*</span></label>
                        <input type="text" id="first_name" name="first_name" class="form-control" placeholder="이름을 입력하세요." value="{{ form.first_name.value|default_if_none:'' }}">
                        {% if form.first_name.errors %}
                        <div class="form-text text-danger">
                            {{ form.first_name.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">이메일 <span class="text-danger">*</span></label>
                        <input type="email" id="email" name="email" class="form-control" placeholder="이메일을 입력하세요." value="{{ form.email.value|default_if_none:'' }}">
                        {% if form.email.errors %}
                        <div class="form-text text-danger">
                            {{ form.email.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                    <div class="mb-3">
                        <label for="username" class="form-label">아이디 <span class="text-danger">*</span></label>
                        <input type="text" id="username" name="username" class="form-control" placeholder="아이디를 입력하세요." value="{{ form.username.value|default_if_none:'' }}">
                        {% if form.username.errors %}
                        <div class="form-text text-danger">
                            {{ form.username.errors.0 }}
                        </div>
                        {% endif %}
                    </div>
                </div>                
            </div>
            <div>
                <button type="submit" class="btn btn-primary">비밀번호 초기화</button>
                <a href="{% url 'auth:find_username' %}" class="btn btn-success">아이디 찾기</a>
                <a href="{% url 'auth:login' %}" class="btn btn-secondary">로그인</a>
            </div>
        </form>
        <!--// 비밀번호 초기화 -->
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        // 비밀번호 초기화 폼 검증
        $('#resetPasswordForm').validate({
            rules: {
                first_name: {
                    required: true,
                },
                email: {
                    required: true,
                },
                username: {
                    required: true,
                }
            },
            messages: {
                first_name: {
                    required: '이름을 입력하세요.',
                },
                email: {
                    required: '이메일을 입력하세요.',
                },
                username: {
                    required: '아이디를 입력하세요.',
                }
            },
            errorClass: 'is-invalid',
            validClass: 'is-valid',
            errorPlacement: function(error, element) {
                error.addClass('invalid-feedback');
                element.closest('.mb-3').append(error);
            },
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>
{% endblock %}